data:
  category: Toys_and_Games
source: amazon18
dataset: Toys_and_Games
user_k: 5
item_k: 5
st_year: 2016
st_month: 10
ed_year: 2018
ed_month: 10
metadata_file: ./raw_data/meta_Toys_and_Games.json
reviews_file: ./raw_data/Toys_and_Games_5.json
output_path: ./data/Amazon18
