kind: rqvae
lr: 0.001
epochs: 10000
batch_size: 20480
num_workers: 4
eval_step: 50
learner: AdamW
lr_scheduler_type: constant
warmup_epochs: 50
data_path: ./data/Amazon/index/Industrial_and_Scientific.emb-qwen-td.npy
ckpt_dir: /data/leejt/OneRec/output_weights/attnrq_identity_lam001
weight_decay: 0.0
dropout_prob: 0.0
bn: false
loss_type: mse
kmeans_init: true
kmeans_iters: 100
num_emb_list: [256, 256, 256]
e_dim: 32
quant_loss_weight: 1.0
beta: 0.25
layers: [2048, 1024, 512, 256, 128, 64]
sk_epsilons: [0.0, 0.0, 0.0]
sk_iters: 50
save_limit: 5
attn_residual_enable: true
attn_residual_mode: dynamic
attn_residual_reg_weight: 0.01
attn_residual_use_rmsnorm: true
attn_residual_temperature: 1.0
