model:
  base_model: ../Qwen3-1.7B
  train_from_scratch: false
data:
  train_file: ./data_experiment/Amazon/toys_baseline_rqvae_onerec_aligned/train/Toys_and_Games_5_2016-10-2018-11.csv
  eval_file: ./data_experiment/Amazon/toys_baseline_rqvae_onerec_aligned/valid/Toys_and_Games_5_2016-10-2018-11.csv
  sid_index_path: ./data_experiment/Amazon/toys_baseline_rqvae_onerec_aligned/index/Toys_and_Games.index.json
  item_meta_path: ./data_experiment/Amazon/toys_baseline_rqvae_onerec_aligned/index/Toys_and_Games.item.json
  category: Toys_and_Games
training:
  batch_size: 1024
  micro_batch_size: 2
  cutoff_len: 512
  enable_title_history2sid_dataset: true
  enable_title_description_alignment: true
  description_task_probability: 0.5
  num_epochs: 10
  learning_rate: 0.0003
  seed: 42
  freeze_llm: false
  group_by_length: false
  warmup_steps: 20
  load_best_model_at_end: true
  early_stopping_patience: 3
  eval_step: 0.05
logging:
  wandb_project: OneRec
  wandb_run_name: sft_toys_baseline_rqvae_onerec_aligned_title_on_desc_p05_4gpu
  report_to: wandb
output:
  output_dir: /data/leejt/OneRec/output_weights/experiments/toys_sft_eval_20260510/baseline_rqvae_onerec_aligned_title_on_desc_p05_4gpu/sft
  save_total_limit: 2
runtime:
  launcher: torchrun
  cuda_visible_devices: "2,3,4,5"
  nproc_per_node: 4
