model:
  base_model: ./output/sft_Industrial_and_Scientific_refactor/final_checkpoint
data:
  test_file: ./data/Amazon/test/Industrial_and_Scientific_5_2016-10-2018-11.csv
  info_file: ./data/Amazon/info/Industrial_and_Scientific_5_2016-10-2018-11.txt
  category: Industrial_and_Scientific
training:
  seed: 42
output:
  output_dir: ./results/final_result_Industrial_and_Scientific.json
batch_size: 8
K: 0
num_beams: 50
max_new_tokens: 256
length_penalty: 0.0
temperature: 1.0
guidance_scale: null
runtime:
  launcher: parallel
  parallel: true
  cuda_visible_devices: "4,5,6,7"
  nproc_per_node: 4
