model:
  base_model: "./output/sft_%{category}_refactor/final_checkpoint"
data:
  train_file: ./data/Amazon/train/%{split_stem}.csv
  eval_file: ./data/Amazon/valid/%{split_stem}.csv
  info_file: ./data/Amazon/info/%{split_stem}.txt
  sid_index_path: ./data/Amazon/index/%{artifact_stem}.index.json
  item_meta_path: ./data/Amazon/index/%{artifact_stem}.item.json
  category: "%{category}"
training:
  seed: 42
  train_batch_size: 16
  eval_batch_size: 32
  gradient_accumulation_steps: 4
  num_epochs: 2
  num_generations: 16
  learning_rate: 0.00001
  eval_step: 0.05
  reward_type: ranking
  temperature: 1.0
  beta: 0.001
  add_gt: false
  beam_search: true
  test_during_training: false
  dynamic_sampling: false
  sync_ref_model: true
  test_beam: 20
  sample_train: false
  dapo: false
  gspo: false
  mask_all_zero: false
  ada_path: ""
  cf_path: ""
logging:
  wandb_project: OneRec
  wandb_run_name: "RL_%{category}_refactor"
  report_to: wandb
output:
  output_dir: "./output/rl_%{category}_refactor"
  save_total_limit: 2
runtime:
  launcher: accelerate
  cuda_visible_devices: "4,5,6,7"
  num_processes: 4
  main_process_port: 29503
  accelerate_config: config/zero2_opt.yaml
  hf_endpoint: https://hf-mirror.com
