model:
  base_model: ../Qwen3-1.7B
  train_from_scratch: false
data:
  train_file: ./data/Amazon/train/Industrial_and_Scientific_5_2016-10-2018-11.csv
  eval_file: ./data/Amazon/valid/Industrial_and_Scientific_5_2016-10-2018-11.csv
  sid_index_path: ./data/Amazon/index/Industrial_and_Scientific.index.json
  item_meta_path: ./data/Amazon/index/Industrial_and_Scientific.item.json
  category: Industrial_and_Scientific
training:
  batch_size: 1024
  micro_batch_size: 4
  cutoff_len: 512
  num_epochs: 10
  learning_rate: 0.0003
  seed: 42
  freeze_llm: false
  group_by_length: false
  warmup_steps: 20
  load_best_model_at_end: true
  early_stopping_patience: 3
  eval_step: 0.05
logging:
  wandb_project: OneRec
  wandb_run_name: sft_Industrial_and_Scientific
  report_to: wandb
output:
  output_dir: ./output/sft_Industrial_and_Scientific_refactor
  save_total_limit: 2
runtime:
  launcher: torchrun
  cuda_visible_devices: "4,5,6,7"
  nproc_per_node: 4
